[platformio]
default_envs = wemos_d1_mini32
;default_envs = lolin_s2_mini
;default_envs = lolin_c3_mini
;default_envs = lolin_s3_mini
;default_envs = d1_mini
;default_envs = d1_mini_pro
;default_envs = esp07s
;default_envs = esp01_1m

[env]
# 用于生成 bin 的时候加前缀
# project_name = test_project222

my_lib_base_path = /Users/fmeng/my_platformio_lib

; arduino-esp32 v3.3.4
; https://github.com/pioarduino/platform-espressif32/tags
platform_esp32_v3_3_4 = file://${env.my_lib_base_path}/arduino-esp32_v3.3.4/platform-espressif32-55.03.34
; https://github.com/espressif/arduino-esp32/tags
platform_packages_esp32_v3_3_4 =
    framework-arduinoespressif32 @ file://${env.my_lib_base_path}/arduino-esp32_v3.3.4/esp32-3.3.4
    framework-arduinoespressif32-libs @ file://${env.my_lib_base_path}/arduino-esp32_v3.3.4/esp32-arduino-libs

# 默认配置
platform_esp32 = ${env.platform_esp32_v3_3_4}
platform_packages_esp32 = ${env.platform_packages_esp32_v3_3_4}

# 脚本
extra_script_main = ${env.my_lib_base_path}/extra_script_main.py
extra_script_extra_script_merge_bin = ${env.my_lib_base_path}/extra_script_merge_bin.py
extra_script_flash_down_tool = ${env.my_lib_base_path}/extra_script_flash_down_tool.py

extra_scripts =
    pre:${env.extra_script_main}

;main_file = EspMapping/examples/EspMapping/EspMapping.ino
;main_file = main_BleTransport.cpp
;main_file = main_IRTransport.cpp
;main_file = main_Dabble_LED.cpp
;main_file = main_Dabble_GamePad.cpp
main_file = main_Dabble_Sensor.cpp

build_flags =
    -w
    -D _TASK_STD_FUNCTION
    -D LOG_DEBUG
    -D DEBUG_LOG

monitor_speed = 115200
;upload_speed = 115200
upload_speed = 921600
;upload_speed = 1500000
;upload_speed = 2000000

lib_deps =
    fmeng/EspMapping
    z3t0/IRremote @ ^4.4.1
    https://github.com/fmeng/DabbleESP32
    ; https://gitee.com/fmeng-no-bug/DabbleESP32

;从 huge_app_littlefs.csv SubType 获取 littlefs
;board_build.filesystem = littlefs
;board_build.partitions = huge_app_littlefs.csv

;从 huge_app_spiffs.csv SubType 获取 spiffs
;board_build.filesystem = spiffs
;board_build.partitions = huge_app_spiffs.csv

[env:wemos_d1_mini32]
platform = ${env.platform_esp32}
platform_packages = ${env.platform_packages_esp32}
board = wemos_d1_mini32
framework = arduino

[env:lolin_s2_mini]
platform = ${env.platform_esp32}
platform_packages = ${env.platform_packages_esp32}
board = lolin_s2_mini
framework = arduino
build_flags =
    ${env.build_flags}
    -D CONFIG_USB_CDC_ENABLED=y

[env:lolin_c3_mini]
platform = ${env.platform_esp32}
platform_packages = ${env.platform_packages_esp32}
board = lolin_c3_mini
framework = arduino
build_unflags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE
    -D ARDUINO_USB_CDC_ON_BOOT

[env:lolin_s3_mini]
platform = ${env.platform_esp32}
platform_packages = ${env.platform_packages_esp32}
board = lolin_s3_mini
framework = arduino
extra_scripts = pre:extra_scripts_main.py
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

[env:d1_mini_pro]
; 16M的flash使用这个配置, 不要在意board的配置
platform = espressif8266
board = d1_mini_pro
framework = arduino

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
upload_resetmethod = nodemcu

[env:esp07s]
platform = espressif8266
board = esp07s
framework = arduino